{% set name = "casacore" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 63f1c8eff932b0fcbd38c598a5811e6e5397b72835b637d6f426105a183b3f91
  patches:
    - ncursesw.patch
    - default-root.patch
    - ignore-build-env-prefix.patch
    - boost-python-cmake.patch
    - clang-link.patch  # [osx]
    - darwin-gettimeofday.patch  # [osx]

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('casacore', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - bison
    - cmake
    - flex
    - make
    - m4
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - boost {{ boost }}
    - cfitsio {{ cfitsio }}
    - fftw {{ fftw }}
    - gsl {{ gsl }}
    - hdf5 {{ hdf5 }}
    - ncurses {{ ncurses }}
    - numpy
    - python
    - readline {{ readline }}
    - wcslib 7.3
  run:
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('numpy') }}
    - ncurses {{ ncurses }}
    - python
    - wcslib 7.3

test:
  commands:
    - casahdf5support
    - findmeastable --help
    - lsmf
    - measuresdata
    - taql --help
    - tomf --help

    # Make sure that libcasa_python doesn't link to libpython on macOS, since
    # then the python-casacore modules will crash -- if binary modules on macOS
    # link to libpython, symbols are duplicated.
    - bash -c "! otool -L $PREFIX/lib/libcasa_python*.5.dylib |grep /libpython"  # [osx]

about:
  home: https://casacore.github.io/casacore/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Core libraries for the Common Astronomical Software Applications (CASA)

extra:
  recipe-maintainers:
    - pkgw
