{% set name = "casacore" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3a714644b908ef6e81489b792cc9b80f6d8267a275e15d38a42a6a5137d39d3d
  patches:
    - ncursesw.patch
    - default-root.patch
    - ignore-build-env-prefix.patch
    - clang-link.patch  # [osx]

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('casacore', max_pin='x.x') }}

requirements:
  build:
    - bison
    - cmake
    - flex
    - m4
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - boost {{ boost }}
    - cfitsio {{ cfitsio }}
    - fftw {{ fftw }}
    - hdf5 {{ hdf5 }}
    - ncurses {{ ncurses }}
    - numpy
    - python
    - readline {{ readline }}
    - wcslib 7.2
  run:
    - boost {{ boost }}
    - ncurses {{ ncurses }}
    - {{ pin_compatible('numpy') }}
    - python
    - wcslib 7.2

test:
  commands:
    - casahdf5support
    - findmeastable --help
    - lsmf
    - measuresdata
    - taql --help
    - tomf --help

    # Make sure that libcasa_python doesn't link to libpython on macOS, since
    # then the python-casacore modules will crash -- if binary modules on macOS
    # link to libpython, symbols are duplicated.
    - bash -c "! otool -L $PREFIX/lib/libcasa_python*.5.dylib |grep /libpython"  # [osx]

about:
  home: https://casacore.github.io/casacore/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'Core libraries for the Common Astronomical Software Applications (CASA)'

extra:
  recipe-maintainers:
    - pkgw
