{% set name = "casacore" %}
{% set version = "2.4.1" %}
{% set sha256 = "58eccc875053b2c6fe44fe53b6463030ef169597ec29926936f18d27b5087d63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ncursesw.patch
    - default-root.patch
    - so-versioning.patch
    - boost-python.patch  # [not py3k]
    - boost-python3.patch  # [py3k]

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - flex
    - bison
    - boost
    - cfitsio 3.430
    - fftw 3.3.*
    - hdf5
    - ncurses
    - numpy        # [py27]
    - numpy        # [py35]
    - numpy         # [py36]
    - openblas
    - python
    - readline
    - wcslib 5.18
  run:
    - boost
    - cfitsio 3.430
    - fftw 3.3.*
    - hdf5
    - ncurses
    - {{ pin_compatible('numpy') }}   # [py27]
    - {{ pin_compatible('numpy') }}   # [py35]
    - {{ pin_compatible('numpy') }}   # [py36]
    - openblas
    - python
    - readline
    - wcslib 5.18

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  license_file: COPYING
  summary: 'Core libraries for the Common Astronomical Software Applications (CASA)'

extra:
  recipe-maintainers:
    - pkgw
