{% set name = "casacore" %}
{% set version = "3.6.0" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% set mpi_prefix = "nompi" %}
{% else %}
{% set mpi_prefix = "mpi_" + mpi %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c88075aa73c2139b323b71a7f5d56cec5a6a0de649efd11e2d00ca033be5a0d7
  patches:
    - ncursesw.patch
    - default-root.patch
    - ignore-build-env-prefix.patch
    - boost-python-cmake.patch
    - 1350.patch  # backport of GitHub #1350 to solve #1348
    - clang-link.patch  # [osx]
    - darwin-gettimeofday.patch  # [osx]
    - libadios2-macos.patch  # [osx]

build:
  number: {{ build }}
  skip: true  # [win]
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('casacore', max_pin='x.x') }}
    - {{ name }} * {{ mpi_prefix }}_*  # [mpi != "nompi"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - bison
    - cmake
    - flex
    - make
    - m4
    - {{ mpi }}  # [mpi == "openmpi" and build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - liblapack
    - libboost-python-devel
    - cfitsio
    - fftw
    - gsl
    - hdf5
    - ncurses
    - numpy
    - python
    - readline
    - wcslib
    - libadios2 2.10 {{ mpi_prefix }}_*  # [mpi != "nompi"]
    - {{ mpi }}  # [mpi != "nompi"]
  run:
    - python
    - {{ mpi }}  # [mpi != "nompi"]

test:
  commands:
    - casahdf5support
    - findmeastable --help
    - lsmf
    - measuresdata
    - taql --help
    - tomf --help

    # Make sure that libcasa_python doesn't link to libpython on macOS, since
    # then the python-casacore modules will crash -- if binary modules on macOS
    # link to libpython, symbols are duplicated.
    - bash -c "! otool -L $PREFIX/lib/libcasa_python*.5.dylib |grep /libpython"  # [osx]

about:
  home: https://casacore.github.io/casacore/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Core libraries for the Common Astronomical Software Applications (CASA)

extra:
  recipe-maintainers:
    - pkgw
